name: deno_postgres_interop_example
description: An example for deno_postgres_interop package.
version: 1.0.0
publish_to: none

environment:
  # https://github.com/invertase/dart_edge/issues/50
  # Tested with 3.0.6, but others should work too
  sdk: '>=3.0.0 <3.1.0'

dependencies:
  deno_postgres_interop:
    path: ..
  edge: ^0.0.5
  supabase_functions: ^0.0.1

dev_dependencies:
  solid_lints: 0.0.19
