name: deno_postgres_interop_example
description: An example for deno_postgres_interop package.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  edge: ^0.0.5
  supabase_functions: ^0.0.1

dev_dependencies:
  solid_lints: 0.0.18
