include: package:solid_lints/analysis_options.yaml

linter:
  rules:
    avoid_classes_with_only_static_members: false
    package_api_docs: true
    prefer_foreach: true
    prefer_single_quotes: true
    public_member_api_docs: true
