include: package:solid_lints/analysis_options.yaml

plugins:
  solid_lints:
    version: ^1.0.0-dev.1
    diagnostics:
      number_of_parameters: false
      cyclomatic_complexity: false
      avoid_non_null_assertion: false
      avoid_duplicate_code: false

linter:
  rules:
    prefer_foreach: true
    prefer_single_quotes: true

