name: deno_postgres_interop
description: An interop for deno-postgres.
version: 0.0.1
repository: https://github.com/solid-software/deno_postgres_interop

environment:
  sdk: ^3.0.0

dev_dependencies:
  solid_lints: 0.0.18
