name: deno_postgres_interop
description: An interop for deno-postgres.
version: 0.0.1
repository: https://github.com/solid-software/deno_postgres_interop

environment:
  # https://github.com/invertase/dart_edge/issues/50
  # Tested with 3.0.6, but others should work too
  sdk: '>=3.0.0 <3.1.0'

dependencies:
  args: ^2.4.2
  collection: ^1.18.0
  yaml: ^3.1.2

dev_dependencies:
  solid_lints: ^0.0.19
