name: deno_postgres_interop
description:
  An interop for js package deno-postgres - PostgreSQL
  driver that can be used in deno-deploy (supabase edge functions).
version: 0.1.0
repository: https://github.com/solid-software/deno_postgres_interop

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.2
  collection: ^1.18.0
  yaml: ^3.1.2

dev_dependencies:
  solid_lints: ^0.0.19

platforms:
  web:
