name: On PR & Push do code check

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'pubspec.yaml'

      - name: Early exit
        if: steps.check_files.outputs.files_exists == 'false'
        run: |
          gh run cancel ${{ github.run_id }}
          gh run watch ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup dart
        uses: dart-lang/setup-dart@v1
        with:
          # https://github.com/invertase/dart_edge/issues/50
          sdk: 3.0.0

      - name: Get main dependencies
        run: dart pub get

      - name: Run static code analysis
        uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-infos: true
      
      # https://github.com/invertase/dart_edge/issues/50
      # dcm action uses stable, which is >=3.1 already, so it doesn't work
      # - name: Dart Code Metrics
      #   uses: solid-software/dart-code-metrics-action@v5
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     fatal_warnings: true
      #     fatal_style: true

      - name: Check formatting
        run: dart format . --set-exit-if-changed
